-- ============================================================
-- Baseline schema — Postgres
-- Tạo toàn bộ bảng hiện tại: product catalog, user, cart, order.
-- ============================================================

-- -------------------- CATEGORY --------------------
CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(512)
);

-- -------------------- USER ------------------------
CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(100),
    name          VARCHAR(128),
    phone         VARCHAR(32),
    provider      VARCHAR(16)  NOT NULL DEFAULT 'LOCAL',
    role          VARCHAR(16)  NOT NULL DEFAULT 'USER',
    google_sub    VARCHAR(64),
    created_at    TIMESTAMP    NOT NULL
);
CREATE INDEX idx_app_user_google_sub ON app_user (google_sub);

-- -------------------- PRODUCT ---------------------
CREATE TABLE product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        VARCHAR(64)   NOT NULL UNIQUE,
    name        VARCHAR(128)  NOT NULL,
    description VARCHAR(1024),
    material    VARCHAR(64),
    price       INT           NOT NULL,
    sale_price  INT,
    badge       VARCHAR(16),
    silhouette  VARCHAR(16)   NOT NULL,
    image_url   VARCHAR(512),
    category_id BIGINT        NOT NULL REFERENCES category (id)
);
CREATE INDEX idx_product_category ON product (category_id);

CREATE TABLE product_color (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    name        VARCHAR(64)  NOT NULL,
    hex_code    VARCHAR(9)   NOT NULL,
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_color_product ON product_color (product_id);

CREATE TABLE product_image (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT       NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    url         VARCHAR(512) NOT NULL,
    alt         VARCHAR(128),
    sort_order  INT          NOT NULL DEFAULT 0
);
CREATE INDEX idx_image_product ON product_image (product_id);

-- -------------------- USER ADDRESS ----------------
CREATE TABLE user_address (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    full_name   VARCHAR(128) NOT NULL,
    phone       VARCHAR(32)  NOT NULL,
    line1       VARCHAR(256) NOT NULL,
    ward        VARCHAR(128),
    district    VARCHAR(128),
    city        VARCHAR(128) NOT NULL,
    note        VARCHAR(512),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL
);
CREATE INDEX idx_user_address_user ON user_address (user_id);

-- -------------------- CART ------------------------
CREATE TABLE cart (
    id          VARCHAR(36)  PRIMARY KEY,
    user_id     BIGINT       REFERENCES app_user (id) ON DELETE SET NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL
);
CREATE INDEX idx_cart_user ON cart (user_id);

CREATE TABLE cart_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id         VARCHAR(36) NOT NULL REFERENCES cart (id) ON DELETE CASCADE,
    product_id      BIGINT      NOT NULL REFERENCES product (id),
    color_name      VARCHAR(64) NOT NULL,
    quantity        INT         NOT NULL,
    price_snapshot  INT         NOT NULL
);
CREATE INDEX idx_cart_item_cart ON cart_item (cart_id);

-- -------------------- ORDER -----------------------
-- `order` là từ khoá Postgres → dùng tên bảng `shop_order`.
CREATE TABLE shop_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(16)  NOT NULL UNIQUE,
    user_id         BIGINT       REFERENCES app_user (id) ON DELETE SET NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    payment_method  VARCHAR(16)  NOT NULL,
    subtotal        INT          NOT NULL,
    shipping_fee    INT          NOT NULL DEFAULT 0,
    total           INT          NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    -- Embedded ShippingAddress (snapshot tại thời điểm đặt)
    ship_name       VARCHAR(128) NOT NULL,
    ship_phone      VARCHAR(32)  NOT NULL,
    ship_line1      VARCHAR(256) NOT NULL,
    ship_ward       VARCHAR(128),
    ship_district   VARCHAR(128),
    ship_city       VARCHAR(128) NOT NULL,
    ship_note       VARCHAR(512)
);
CREATE INDEX idx_order_user ON shop_order (user_id);
CREATE INDEX idx_order_status ON shop_order (status);

CREATE TABLE order_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL REFERENCES shop_order (id) ON DELETE CASCADE,
    product_id   BIGINT       NOT NULL REFERENCES product (id),
    product_name VARCHAR(128) NOT NULL,
    color_name   VARCHAR(64)  NOT NULL,
    quantity     INT          NOT NULL,
    unit_price   INT          NOT NULL
);
CREATE INDEX idx_order_item_order ON order_item (order_id);
